export const PERMISSIONS = [
  { id: "INTERNET", label: "Internet Access", icon: "Globe", group: "Network" },
  { id: "ACCESS_NETWORK_STATE", label: "Network State", icon: "Signal", group: "Network" },
  { id: "ACCESS_WIFI_STATE", label: "WiFi State", icon: "Wifi", group: "Network" },
  { id: "CAMERA", label: "Camera", icon: "Camera", group: "Hardware" },
  { id: "RECORD_AUDIO", label: "Microphone", icon: "Mic", group: "Hardware" },
  { id: "VIBRATE", label: "Vibrate", icon: "Smartphone", group: "Hardware" },
  { id: "FLASHLIGHT", label: "Flashlight", icon: "Zap", group: "Hardware" },
  { id: "BLUETOOTH", label: "Bluetooth", icon: "Bluetooth", group: "Hardware" },
  { id: "READ_EXTERNAL_STORAGE", label: "Read Storage", icon: "Folder", group: "Storage" },
  { id: "WRITE_EXTERNAL_STORAGE", label: "Write Storage", icon: "HardDrive", group: "Storage" },
  { id: "MANAGE_EXTERNAL_STORAGE", label: "Manage All Files", icon: "Database", group: "Storage" },
  { id: "ACCESS_FINE_LOCATION", label: "Precise Location", icon: "MapPin", group: "Location" },
  { id: "ACCESS_COARSE_LOCATION", label: "Approximate Location", icon: "Map", group: "Location" },
  { id: "ACCESS_BACKGROUND_LOCATION", label: "Background Location", icon: "Compass", group: "Location" },
  { id: "READ_CONTACTS", label: "Read Contacts", icon: "Users", group: "Personal" },
  { id: "WRITE_CONTACTS", label: "Write Contacts", icon: "Edit", group: "Personal" },
  { id: "READ_CALL_LOG", label: "Call Log", icon: "Phone", group: "Personal" },
  { id: "SEND_SMS", label: "Send SMS", icon: "MessageSquare", group: "Personal" },
  { id: "RECEIVE_SMS", label: "Receive SMS", icon: "Inbox", group: "Personal" },
  { id: "READ_PHONE_STATE", label: "Phone State", icon: "Smartphone", group: "Personal" },
  { id: "USE_BIOMETRIC", label: "Biometrics", icon: "Lock", group: "Security" },
  { id: "USE_FINGERPRINT", label: "Fingerprint", icon: "Hand", group: "Security" },
  { id: "FOREGROUND_SERVICE", label: "Foreground Service", icon: "Settings", group: "System" },
  { id: "RECEIVE_BOOT_COMPLETED", label: "Start on Boot", icon: "Rocket", group: "System" },
  { id: "WAKE_LOCK", label: "Wake Lock", icon: "Battery", group: "System" },
  { id: "POST_NOTIFICATIONS", label: "Notifications", icon: "Bell", group: "System" },
  { id: "SCHEDULE_EXACT_ALARM", label: "Exact Alarms", icon: "Clock", group: "System" },
  { id: "BILLING", label: "In-App Purchases", icon: "CreditCard", group: "Billing" },
];

export const DEPENDENCIES = [
  { id: "retrofit", label: "Retrofit 2", version: "2.9.0", desc: "HTTP client", group: "Networking" },
  { id: "okhttp", label: "OkHttp 4", version: "4.12.0", desc: "HTTP & WebSocket", group: "Networking" },
  { id: "glide", label: "Glide", version: "4.16.0", desc: "Image loading", group: "Media" },
  { id: "picasso", label: "Picasso", version: "2.8", desc: "Image loading alt", group: "Media" },
  { id: "exoplayer", label: "ExoPlayer", version: "2.19.1", desc: "Media playback", group: "Media" },
  { id: "room", label: "Room DB", version: "2.6.1", desc: "SQLite abstraction", group: "Database" },
  { id: "realm", label: "Realm", version: "10.18.0", desc: "Mobile database", group: "Database" },
  { id: "firebase-core", label: "Firebase Core", version: "32.7.4", desc: "Firebase base", group: "Firebase" },
  { id: "firebase-auth", label: "Firebase Auth", version: "22.3.1", desc: "Authentication", group: "Firebase" },
  { id: "firebase-firestore", label: "Firestore", version: "24.10.3", desc: "Cloud database", group: "Firebase" },
  { id: "firebase-storage", label: "Firebase Storage", version: "20.3.0", desc: "File storage", group: "Firebase" },
  { id: "firebase-fcm", label: "FCM Push", version: "23.4.1", desc: "Push notifications", group: "Firebase" },
  { id: "hilt", label: "Hilt DI", version: "2.50", desc: "Dependency injection", group: "Architecture" },
  { id: "lifecycle", label: "Lifecycle", version: "2.7.0", desc: "Lifecycle-aware", group: "Architecture" },
  { id: "navigation", label: "Navigation", version: "2.7.7", desc: "Fragment navigation", group: "Architecture" },
  { id: "datastore", label: "DataStore", version: "1.0.0", desc: "Key-value storage", group: "Architecture" },
  { id: "compose", label: "Jetpack Compose", version: "1.6.2", desc: "Modern UI toolkit", group: "UI" },
  { id: "material3", label: "Material 3", version: "1.2.0", desc: "Material Design 3", group: "UI" },
  { id: "lottie", label: "Lottie", version: "6.4.0", desc: "Animations", group: "UI" },
  { id: "maps", label: "Google Maps", version: "18.2.0", desc: "Maps SDK", group: "Location" },
  { id: "location", label: "Play Location", version: "21.2.0", desc: "Fused location", group: "Location" },
  { id: "stripe", label: "Stripe SDK", version: "20.40.0", desc: "Payments", group: "Payments" },
  { id: "billing", label: "Play Billing", version: "6.2.1", desc: "In-app purchases", group: "Payments" },
  { id: "ml-kit", label: "ML Kit", version: "18.0.0", desc: "Machine learning", group: "AI/ML" },
  { id: "tensorflow", label: "TensorFlow Lite", version: "2.14.0", desc: "On-device ML", group: "AI/ML" },
];

export const GROUPS_PERM = [...new Set(PERMISSIONS.map(p => p.group))];
export const GROUPS_DEP = [...new Set(DEPENDENCIES.map(d => d.group))];
